DROP TABLE IF EXISTS ALERTS;
DROP TABLE IF EXISTS USERS;
-- DROP TABLE IF EXISTS WEATHER;

CREATE TABLE ALERTS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_email BOOLEAN NOT NULL,
    is_phone_number BOOLEAN NOT NULL,
    latitude REAL NOT NULL,
    longitude REAL NOT NULL,
    location VARCHAR(255) NOT NULL,
    operator VARCHAR(3) NOT NULL,
    threshold REAL NOT NULL,
    user_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);


CREATE TABLE USERS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone_number VARCHAR(20) NOT NULL,
    password VARCHAR(20) NOT NULL
);

