DROP TABLE IF EXISTS ALERTS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS WEATHER;

CREATE TABLE ALERTS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone_number VARCHAR(20) NOT NULL
);

CREATE TABLE USERS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    coordinates POINT NOT NULL SRID 4326,
    condition_type VARCHAR(20),
    operator VARCHAR(3),
    threshold REAL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
